Everything for Task Entity
tel-ran-de/business-tracker pull request #1
Opened 2021-05-27 18:37 UTC by gulnara-b

2021-05-28 09:45 UTC, sharf85 requested changes

2021-05-28 09:45 UTC, sharf85 commented on business-tracker-api/build.gradle
> +//    implementation 'org.flywaydb:flyway-core:7.9.1'
why?

2021-05-28 09:45 UTC, sharf85 commented on .gitignore
> +### Postgres de.telran.businesstracker.data ###
What is this? You must follow what you're committing

2021-05-28 09:45 UTC, sharf85 commented on business-tracker-api/build.gradle
> +//    implementation 'org.flywaydb:flyway-core:7.9.1'
Ok, we can leave it for now

2021-05-28 09:45 UTC, sharf85 commented on business-tracker-api/src/main/java/de/telran/businesstracker/data/Member.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
take "sequenсe" for all entities

2021-05-28 09:45 UTC, sharf85 commented on business-tracker-api/src/main/java/de/telran/businesstracker/data/Project.java
> +    @Column(name = "name")
why?

2021-05-28 09:45 UTC, sharf85 commented on business-tracker-api/src/main/java/de/telran/businesstracker/data/Resource.java
> +    @Column(name = "name")
why do you use this annotation for all entities?

2021-05-28 09:45 UTC, sharf85 commented on business-tracker-api/src/main/java/de/telran/businesstracker/data/User.java
> +@Table(name = "jhi_user")
just name this "users" =) jhi - means jhipster

2021-05-28 09:45 UTC, sharf85 commented on business-tracker-api/src/main/java/de/telran/businesstracker/service/TaskService.java
> +public class TaskService {
test all methods with mockito - you were right

2021-05-28 09:45 UTC, sharf85 commented on business-tracker-api/src/main/java/de/telran/businesstracker/controller/TaskController.java
> +        if (!Objects.equals(id, task.getId())) {
what is this? this is maslo maslyanoe

2021-05-28 09:45 UTC, sharf85 commented on business-tracker-api/src/main/java/de/telran/businesstracker/controller/TaskController.java
> +        if (!Objects.equals(id, task.getId())) {
remove this to dicks...

2021-05-28 09:45 UTC, sharf85 commented on business-tracker-api/src/main/java/de/telran/businesstracker/controller/TaskController.java
> +        Optional<Task> task = Optional.ofNullable(taskService.getById(id));
why? did you test it?

2021-06-01 21:29 UTC, AR1988 commented on business-tracker-api/src/main/java/de/telran/businesstracker/controller/MemberController.java
> +@Transactional
Do we need this here?

2021-06-01 21:30 UTC, AR1988 commented on business-tracker-api/src/main/java/de/telran/businesstracker/controller/MilestoneController.java
> +@Transactional
Do we need this here?

2021-06-02 11:17 UTC, sharf85 approved these changes

2021-06-02 12:10 UTC, AR1988 requested changes

2021-06-02 12:10 UTC, AR1988 commented on business-tracker-api/src/main/java/de/telran/businesstracker/data/Milestone.java
> +    private Roadmap roadmap;
Need 
```
@ElementCollection
List<String> kpis
```

2021-06-02 12:10 UTC, AR1988 commented on business-tracker-api/src/main/java/de/telran/businesstracker/controller/MilestoneController.java
> +public class MilestoneController {
need enpoints

1. get all kpi by MileStoneId
2. get all kpi by ProjectId
3. remove kpi by kpi name

2021-06-02 12:10 UTC, AR1988 commented on business-tracker-api/src/main/java/de/telran/businesstracker/service/MilestoneService.java
> +
kpis methodos: add, remove, getAllKpisBy - ProjectId, MileStoneId

2021-06-02 13:36 UTC, AR1988 requested changes

2021-06-02 13:36 UTC, AR1988 commented on business-tracker-api/src/main/java/de/telran/businesstracker/controller/TaskController.java
> +public class TaskController {
need endpoints:
get all tasks by **MilestoneId**
get all tasks by **taskIsActive** true

2021-06-02 13:36 UTC, AR1988 commented on business-tracker-api/src/main/java/de/telran/businesstracker/data/Milestone.java
> +public class Milestone {
need enpoints: 
get all milestones by **ProjectId**

2021-06-02 13:36 UTC, AR1988 commented on business-tracker-api/src/main/java/de/telran/businesstracker/data/Milestone.java
> +    private LocalDate finishDate;
need field 
`Boolean active`

2021-06-02 13:36 UTC, AR1988 commented on business-tracker-api/src/main/java/de/telran/businesstracker/controller/ResourceController.java
> +public class ResourceController {
need enpoints:
1.  get all resources by **TaskId**
2. get all resources by **ProjectId**

2021-06-02 13:36 UTC, AR1988 commented on business-tracker-api/src/main/java/de/telran/businesstracker/controller/MemberController.java
> +public class MemberController {
need endpoint:

1. get memeber by taskId
2. get members by ProjectId

2021-06-02 13:51 UTC, merged